name: OptimaV2 CI

env:
  REGISTRY_NAME: "ezcr.enerzai.com"
  VERSION: "1.0.2"

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main", "dev"]

jobs:
  layertest:
    runs-on: [ self-hosted, linux, Garnet ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Test_layer
        shell: bash
        run: |
          docker run --rm -t -v ~/.ssh/id_ed25519.pub:/root/.ssh/id_rsa.pub -v ~/.ssh/id_ed25519:/root/.ssh/id_rsa -v ${{ github.workspace }}:/workspace/benchmark python:3.10.14-bullseye /bin/sh -c "cd /workspace/benchmark && git config --global --add safe.directory /workspace/benchmark && ./run.sh"

      - name: Git push result
        run: |
          git config --global user.name 'enerzai'
          git config --global user.email 'enerzai@enerzai.com'
          git add ciout/result.md
          git commit -m "[skip ci] result.md updated."
          git push

      - name: Change owner byproucts
        if : always()
        shell: bash
        run: docker run --rm -e "USERID=$(id -u)" -e "GROUPID=$(id -g)" -t -v ${{ github.workspace }}:/workspace/benchmark python:3.10.14-bullseye /bin/sh -c "chown -R $USERID:$GROUPID /workspace/benchmark" 