name: OptimaV2 CI

env:
  REGISTRY_NAME: "ezcr.enerzai.com"
  VERSION: "1.0.2"

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  layertest:
    runs-on: [ self-hosted, linux, Garnet ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Test_layer
        shell: bash
        run: |
          docker run --rm -t -v ${{ github.workspace }}:/workspace/benchmark python:3.10.14-bullseye /bin/sh -c "cd /workspace/benchmark && ./run.sh"